name: Functions CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: root
        run: ln -s usr/bin bin ; bash &

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Use Node.js LTS
        run: |
          yarn --version
          node --version
          
      - name: Cache Yarn dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: implementation/twitter-verification/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: implementation/twitter-verification
        run: yarn install

      - name: Deploy
        working-directory: implementation/twitter-verification
        run: yarn hardhat deploy > deploy_output.txt

      - name: Parse deploy output
        id: parse_output
        run: |
          OUTPUT=$(cat implementation/twitter-verification/deploy_output.txt)
          # Parse the output as needed and set desired environment variables or use the output in subsequent steps
          echo "Parsed output: $OUTPUT"

      - name: Run setup-client.js
        working-directory: implementation/twitter-verification
        run: yarn hardhat run scripts/setup-client.js

      - name: Run execute-request.js
        working-directory: implementation/twitter-verification
        run: yarn hardhat run scripts/execute-request.js
