name: Functions CI

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up working directory
        run: |
          cd implementation/twitter-verification

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run:  cd implementation/twitter-verification && yarn 

      - name: compile
        run:  cd implementation/twitter-verification && yarn hardhat deploy
        
      - name: client
        run:  cd implementation/twitter-verification && yarn hardhat run scripts/setup-client.js 
        
              
      - name: request
        run:  cd implementation/twitter-verification && yarn hardhat run scripts/execute-request.js 
