name: Functions CI
on:
  push:
    branches:
      - main
jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run:  cd implementation/twitter-verification ; yarn 
      - name: Deploy
        run: cd implementation/twitter-verification ; yarn hardhat deploy > deploy_output.txt
      - name: Parse deploy output
        id: parse_output
        run: |
          OUTPUT=$(cat implementation/twitter-verification/deploy_output.txt)
          # Parse the output as needed and set desired environment variables or use the output in subsequent steps
          echo "Parsed output: $OUTPUT"
      - name: client
        run: cd implementation/twitter-verification ; yarn hardhat run scripts/setup-client.js 
      - name: request
        run: cd implementation/twitter-verification ; yarn hardhat run scripts/execute-request.js 
